---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, service connectors, what are connectors, what is a connector, what"s a connector, days, 14 days' 
summary: 대부분의 경우 클라우드나 온프레미스 네트워크에 커넥터를 구축해야 합니다. Connector를 사용하면 Cloud Manager에서 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있습니다. 
---
= 커넥터에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
대부분의 경우 계정 관리자는 클라우드 또는 온-프레미스 네트워크에 _Connector_를 배포해야 합니다. Connector는 Cloud Manager의 일상적인 사용에 있어 중요한 구성요소입니다. Connector를 사용하면 Cloud Manager에서 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있습니다.



== 커넥터가 필요한 경우

Connector는 Cloud Manager의 다양한 기능과 서비스를 사용하는 데 필요합니다.



=== 서비스

* ONTAP용 Amazon FSx 관리 기능
* Amazon S3 버킷 검색
* 클라우드 백업
* 클라우드 데이터 감지
* 클라우드 계층화
* Cloud Volumes ONTAP
* 글로벌 파일 캐시
* Kubernetes 클러스터
* 모니터링
* 온프레미스 ONTAP 클러스터


커넥터는 *_NOT_ * 다음 서비스에 필요합니다.

* Active IQ 디지털 자문업체
* ONTAP 작업 환경을 위한 Amazon FSx 커넥터 가 작업 환경을 생성할 필요가 없는 경우, 볼륨 생성 및 관리, 데이터 복제, ONTAP용 FSx 를 데이터 감지 및 Cloud Sync 와 같은 NetApp 클라우드 서비스와 통합해야 합니다.
* Azure NetApp Files
+
Azure NetApp Files를 설정하고 관리하는 데 커넥터가 필요하지 않지만 클라우드 데이터 센스를 사용하여 Azure NetApp Files 데이터를 스캔하려면 커넥터가 필요합니다.

* Google Cloud용 Cloud Volumes Service
* Cloud Sync




=== 디지털 지갑

거의 모든 경우에 Connector 없이 디지털 지갑에 라이센스를 추가할 수 있습니다.

디지털 지갑에 라이센스를 추가하는 데 커넥터가 필요한 유일한 시간은 Cloud Volumes ONTAP_node-based_licenses입니다. 이 경우 Cloud Volumes ONTAP 시스템에 설치된 라이센스에서 데이터를 가져왔기 때문에 커넥터가 필요합니다.



== 지원되는 위치

커넥터는 다음 위치에서 지원됩니다.

* Amazon Web Services에서 직접 지원합니다
* Microsoft Azure를 참조하십시오
* Google 클라우드
* 온프레미스
* 인터넷 접속 없이 구내




=== Azure 배포에 대한 참고 사항

Azure에 커넥터를 배포하는 경우, 커넥터가 관리하는 Cloud Volumes ONTAP 시스템과 동일한 Azure 영역에 배포되거나 에 배포되어야 합니다 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 지역 쌍"^] Cloud Volumes ONTAP 시스템의 경우 이 요구 사항은 Cloud Volumes ONTAP와 연결된 스토리지 계정 간에 Azure 전용 링크 연결이 사용되도록 합니다. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAP에서 Azure 프라이빗 링크를 사용하는 방법에 대해 알아보십시오"^].



=== Google Cloud 배포에 대한 참고 사항

Google Cloud에서 Cloud Volumes ONTAP 시스템을 만들려면 Google Cloud에서도 실행되는 커넥터가 있어야 합니다. AWS, Azure 또는 온프레미스에서 실행되는 Connector를 사용할 수 없습니다.



== 커넥터는 계속 작동 중이어야 합니다

커넥터는 항상 작동 상태를 유지해야 합니다. 이는 여러분이 제공하는 서비스의 지속적인 상태 및 운영에 중요합니다.

예를 들어, Connector는 Cloud Volumes ONTAP PAYGO 시스템의 상태 및 작동에 있어 핵심 구성 요소입니다. 커넥터가 꺼져 있는 경우, Cloud Volumes ONTAP PAYGO 시스템은 커넥터와의 통신이 14일 이상 끊긴 후 종료됩니다.



== 커넥터 작성 방법

작업 영역 관리자가 Cloud Volumes ONTAP 작업 환경을 만들고 위에 나열된 다른 서비스를 사용하려면 계정 관리자가 커넥터를 만들어야 합니다.

계정 관리자는 다음과 같은 여러 가지 방법으로 커넥터를 만들 수 있습니다.

* Cloud Manager에서 직접(권장)
+
** link:task-creating-connectors-aws.html["AWS에서 생성"]
** link:task-creating-connectors-azure.html["Azure에서 생성"]
** link:task-creating-connectors-gcp.html["GCP에서 생성"]


* 자체 Linux 호스트에 소프트웨어를 수동으로 설치합니다
+
** link:task-installing-linux.html["인터넷에 액세스할 수 있는 호스트"]
** link:task-install-connector-onprem-no-internet.html["인터넷에 액세스할 수 없는 온프레미스 호스트입니다"]


* 더 높은 경쟁력을 강화할 수 있습니다
+
** link:task-launching-aws-mktp.html["AWS 마켓플레이스 를 참조하십시오"]
** link:task-launching-azure-mktp.html["Azure 마켓플레이스 를 참조하십시오"]




작업을 완료하는 데 필요한 경우 Cloud Manager에서 커넥터를 생성하라는 메시지가 표시됩니다.



== 권한

Connector를 만들려면 특정 권한이 필요하며 Connector 인스턴스 자체에 다른 권한 집합이 필요합니다.



=== Connector를 만들 수 있는 권한

Cloud Manager에서 Connector를 생성하는 사용자는 선택한 클라우드 공급자에 인스턴스를 배포하기 위한 특정 권한이 필요합니다. Cloud Manager는 Connector를 생성할 때 권한 요구 사항을 상기시킵니다.

https://mysupport.netapp.com/site/info/cloud-manager-policies["각 클라우드 공급자에 대한 정책을 봅니다"^].



=== Connector 인스턴스에 대한 권한

Connector는 사용자를 대신하여 작업을 수행하려면 특정 클라우드 공급자 권한이 필요합니다. 예를 들어, Cloud Volumes ONTAP를 구축하고 관리하는 경우를 들 수 있습니다.

Cloud Manager에서 직접 Connector를 생성하면 Cloud Manager에서 필요한 권한이 있는 Connector가 생성됩니다. 당신이 해야 할 일은 아무것도 없습니다.

AWS Marketplace, Azure Marketplace 또는 소프트웨어를 수동으로 설치하여 직접 Connector를 생성하는 경우 올바른 권한이 있는지 확인해야 합니다.

https://mysupport.netapp.com/site/info/cloud-manager-policies["각 클라우드 공급자에 대한 정책을 봅니다"^]



== 커넥터 업그레이드

일반적으로 매월 커넥터 소프트웨어를 업데이트하여 새로운 기능을 소개하고 안정성 향상을 제공합니다. Cloud Manager 플랫폼의 대부분의 서비스와 기능은 SaaS 기반 소프트웨어를 통해 제공되지만, Connector의 버전에 따라 몇 가지 기능이 달라집니다. 여기에는 Cloud Volumes ONTAP 관리, 온프레미스 ONTAP 클러스터 관리, 설정 및 도움말이 포함됩니다.

Connector는 소프트웨어가 있는 한 소프트웨어를 최신 버전으로 자동 업데이트합니다 link:reference-networking-cloud-manager.html["아웃바운드 인터넷 액세스"] 를 클릭하여 소프트웨어 업데이트를 얻습니다.



== 커넥터당 작업 환경 수

Connector는 Cloud Manager에서 여러 작업 환경을 관리할 수 있습니다. 단일 커넥터가 관리해야 하는 최대 작업 환경 수는 서로 다릅니다. 운영 환경의 유형, 볼륨 수, 관리되는 용량 및 사용자 수에 따라 달라집니다.

대규모 구축이 있는 경우 NetApp 담당자와 협력하여 환경을 사이징합니다. 도중에 문제가 발생하는 경우 제품 내 채팅을 통해 문의해 주십시오.



== 여러 커넥터를 사용하는 경우

경우에 따라 하나의 커넥터만 필요할 수 있지만 둘 이상의 커넥터가 필요할 수 있습니다.

다음은 몇 가지 예입니다.

* 멀티 클라우드 환경(AWS 및 Azure)을 사용 중이라면 AWS에, Azure에 각각 Connector를 설치하고, 각 는 이러한 환경에서 실행되는 Cloud Volumes ONTAP 시스템을 관리합니다.
* 서비스 공급자는 NetApp 계정 하나를 사용하여 고객에게 서비스를 제공하는 한편, 다른 계정을 사용하여 부서 중 하나에 대해 재해 복구를 제공할 수 있습니다. 각 계정에는 별도의 커넥터가 있습니다.




== 동일한 작업 환경에서 여러 커넥터 사용

재해 복구를 위해 여러 커넥터가 있는 작업 환경을 동시에 관리할 수 있습니다. 하나의 커넥터가 다운되면 다른 커넥터로 전환하여 작업 환경을 즉시 관리할 수 있습니다.

이 구성을 설정하려면 다음을 수행하십시오.

. link:task-managing-connectors.html["다른 커넥터로 전환합니다"]
. 기존 작업 환경을 파악합니다.
+
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html["기존 Cloud Volumes ONTAP 시스템을 Cloud Manager에 추가합니다"^]
** https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["ONTAP 클러스터에 대해 알아보십시오"^]


. 를 설정합니다 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html["용량 관리 모드"^]
+
주 커넥터만 * 자동 모드 * 로 설정해야 합니다. DR 목적으로 다른 커넥터로 전환하면 필요에 따라 용량 관리 모드를 변경할 수 있습니다.





== 커넥터 간 전환 시기

첫 번째 Connector를 만들면 Cloud Manager는 사용자가 생성한 각 추가 작업 환경에 대해 해당 Connector를 자동으로 사용합니다. 추가 커넥터를 만든 후에는 각 Connector에 해당하는 작업 환경을 보기 위해 커넥터 사이를 전환해야 합니다.

link:task-managing-connectors.html["커넥터 간 전환 방법에 대해 알아보십시오"].



== 로컬 사용자 인터페이스입니다

에서 거의 모든 작업을 수행해야 합니다 https://cloudmanager.netapp.com["SaaS 사용자 인터페이스"^]로컬 사용자 인터페이스는 Connector에서 계속 사용할 수 있습니다. 이 인터페이스는 인터넷에 액세스할 수 없는 환경에 Connector를 설치하고 SaaS 인터페이스 대신 Connector 자체에서 수행해야 하는 몇 가지 작업에 필요합니다.

* link:task-configuring-proxy.html["프록시 서버 설정"]
* 패치 설치(일반적으로 NetApp 직원과 협력하여 패치 설치)
* AutoSupport 메시지 다운로드(일반적으로 문제가 있을 때 NetApp 담당자가 지시)


link:task-managing-connectors.html#access-the-local-ui["로컬 UI에 액세스하는 방법을 알아보십시오"].
